version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - TZ=America/Sao_Paulo  
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro

    command: >
      /bin/sh -c "
      flask db init || true &&
      flask db migrate -m 'Inicialização' || true &&
      flask db upgrade || true &&
      flask run --host=0.0.0.0"




