"""Inicialização

Revision ID: bb44460c5083
Revises: d0d554ee7db0
Create Date: 2024-10-30 21:31:39.206288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb44460c5083'
down_revision = 'd0d554ee7db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_second_number', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('notify_second_number')

    # ### end Alembic commands ###
