"""Inicialização

Revision ID: d0d554ee7db0
Revises: 212b44dbd052
Create Date: 2024-10-30 20:44:34.212281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d554ee7db0'
down_revision = '212b44dbd052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notified_one_hour', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('notified_one_hour')

    # ### end Alembic commands ###
